services:
  frontend:
    build: ./frontend
    image: databridge-frontend:latest
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://localhost:3002
    depends_on:
      - backend

  backend:
    build: ./backend
    image: databridge-backend:latest
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/databridge
      - PORT=3002
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
